# travis ci
language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "2.5"
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script:  nosetests tests