language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - FLASK=0.8.1
  - FLASK=0.9
  - FLASK=0.10.1

matrix:
  exclude:
   - python: "3.3"
     env: FLASK=0.8.1
   - python: "3.3"
     env: FLASK=0.9
   - python: "3.4"
     env: FLASK=0.8.1
   - python: "3.4"
     env: FLASK=0.9

# command to install dependencies
install:
  - pip install -q Flask==$FLASK 
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -r requirements-contrib.txt
  - pip install python-coveralls

# command to run tests
script:
  # pytest coverage bombs on pypy idk
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then py.test tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then py.test --cov flask_featureflags --cov-report term-missing tests; fi

after_success:
  - coveralls